name: jhatpat
description: A Cab Booking App

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.0.0-dev.9
  geolocator: ^9.0.1
  location: ^4.4.0
  google_maps_flutter: ^2.1.12
  flutter_polyline_points: ^1.0.0
  flutter_google_places_hoc081098: ^1.1.0
  geocoding: ^2.0.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  webview_flutter: ^3.0.4
  pinput: ^2.2.12
  device_info_plus: ^4.1.2
  platform_device_id: ^1.0.1
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  paytm_allinonesdk: ^1.1.8
  url_launcher: ^6.1.5
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  # flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_icons:
#   image_path: "assets/logo/logo.jpg"
#   android: "launcher_icon"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
